[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]

reqwest = { version = "0.12.9", features = ["blocking", "json"] }
scraper = "0.21.0"
tokio = { version = "1.42.0", features = ["full"] }
